name = "invoice-generator"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Routes for custom domain (optional)
# routes = [
#   { pattern = "yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "INVOICE_DATA"
preview_id = "preview_invoice_data_kv"
id = "production_invoice_data_kv"

# Variables (can be set via Cloudflare dashboard or wrangler secret)
[vars]
ENVIRONMENT = "production"
APP_VERSION = "2.0.0"
MAX_INVOICES_PER_USER = "1000"
DEFAULT_CACHE_TTL = "3600"

# Environment-specific configurations
[env.production]
name = "invoice-generator-prod"

[env.staging]
name = "invoice-generator-staging"
vars = { ENVIRONMENT = "staging" }

[env.development]
name = "invoice-generator-dev"
vars = { ENVIRONMENT = "development" }

# Build configuration
[build]
command = "echo 'No build step required'"
watch_dir = ["worker.js", "wrangler.toml"]

# Miniflare configuration for local development
[miniflare]
kv_persist = true
upstream = "https://invoice-generator.pages.dev"

# Analytics and monitoring
[analytics_engine_datasets]
[[analytics_engine_datasets.bindings]]
name = "ANALYTICS"
dataset = "invoice_analytics"

# Durable Objects (for future use)
# [[durable_objects.bindings]]
# name = "INVOICE_SESSIONS"
# class_name = "InvoiceSession"
# script_name = "invoice-generator"

# R2 Buckets (for future PDF storage)
# [[r2_buckets]]
# binding = "INVOICE_PDFS"
# bucket_name = "invoice-generator-pdfs"
# preview_bucket_name = "invoice-generator-pdfs-preview"

# Scheduled triggers for maintenance
[[triggers.crons]]
cron = "0 2 * * *"
handler = "scheduled"

# Size limits and performance
[limits]
cpu_ms = 30000
memory_mb = 128

# Security headers
[site]
bucket = "./dist"
entry-point = "./"
include = ["**/*"]
exclude = [".git/**", "node_modules/**", "*.md", "package*.json"]

# Custom headers for security
[env.production.vars]
SECURITY_HEADERS = "true"
CSP_POLICY = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self';"

# Development-specific settings
[env.development.vars]
DEBUG = "true"
LOG_LEVEL = "debug"