name = "invoice-generator"
compatibility_date = "2025-10-20"
pages_build_output_dir = "."

[vars]
APP_VERSION = "2.0.3"
ENVIRONMENT = "production"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "invoice-generator"
database_id = "e4dbcc4b-04fc-4444-a0f1-abe3c3f27d4c"
