# Cloudflare Pages configuration
# This file is for Pages builds (not Workers). It must be valid TOML.

[vars]
APP_VERSION = "2.0.2"

# Output directory for Pages (use repository root for static site)
pages_build_output_dir = "."

# If later using Functions for Pages, specify directory:
# functions = "functions"

# For Workers (separate), create wrangler.worker.toml instead of this file.
